<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CustommerAddress extends Model
{
    /**
     * @var string
     */
    protected $table = 'customer_addresses';

    /**
     * @var array
     */
    protected $fillable = [
        'customer_id',
        'recipient_name',
        'recipient_phone',
        'province_code',
        'city_code',
        'county_code',
        'detailed',
        'last_used',
        'is_default'
    ];

    /**
     * @var array
     */
    protected $casts = [
        'is_default' => 'boolean'
    ];

    public function setIsDefaultAttribute($val)
    {
        $this->attributes['is_default'] = $val ? 1 : 0;
    }

    public function setProvinceCodeAttribute($val)
    {
        $this->attributes['province_code'] = str_pad($val, 6, 0, STR_PAD_RIGHT);
    }

    public function setCityCodeAttribute($val)
    {
        $this->attributes['city_code'] = str_pad($val, 6, 0, STR_PAD_RIGHT);
    }

    public function setCountyCodeAttribute($val)
    {
        $this->attributes['county_code'] = str_pad($val, 6, 0, STR_PAD_RIGHT);
    }

    public function save(array $options = [])
    {
//        dd($this->getAttributes());
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}